name: Build
on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git subversion git-core wget
          sudo timedatectl set-timezone "$TZ"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
        
      - uses: actions/setup-node@v2
        with:
         node-version: 16
      - uses: bahmutov/npm-install@v1
      - run: npm run prepare
      
      - name: Update
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/add-to-web3
          git add 'dist'
          git commit -m "update dist $(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --quiet "https://${{ secrets.TOKEN }}@github.com/ykxVK8yL5L/add-to-web3.git"
